---
- name: Setup workstation
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:
  - name: setup_secrets
    prompt: "Decrypt and install secrets? (yes/no)"
    default: "no"
    private: no

  pre_tasks:
  - name: Detect OS
    ansible.builtin.set_fact:
      is_macos: "{{ ansible_os_family == 'Darwin' }}"
      is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  
  roles:
  - role: common
  - role: macos
    when: is_macos
  - role: ubuntu
    when: is_ubuntu
  - role: shell
  - role: terminal
  - role: neovim
  - role: dev-tools
  - role: secrets
    when: setup_secrets | bool
